services:
  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:3567:3567"
    env_file:
      - ./.env
      - ./backend/.env
    volumes:
      - garmin_session_data:/app/app/garmin/session_data

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: https://garmin.beraud.dev
    ports:
      - "127.0.0.1:3568:3568"
    depends_on:
      - backend

volumes:
  garmin_session_data:
